<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net472</TargetFramework>
    <AssemblyName>BetterPawnControlForked</AssemblyName>
    <RootNamespace>BetterPawnControlForked</RootNamespace>
    <Title>Better Pawn Control Forked</Title>
    <Description>Better Pawn Control Forked RimWorld Mod</Description>
    <OutputPath>..\v1.6\Assemblies\</OutputPath>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <Copyright>Copyright © 2025</Copyright>
    <RepositoryUrl>https://github.com/KyleMHB/BetterPawnControlForked</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <Authors>KyleMHB</Authors>
    <Version>2.8.1</Version>
  </PropertyGroup>

  <ItemGroup>
    <None Include="..\README.md">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Krafs.Publicizer" Version="2.3.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Krafs.Rimworld.Ref" Version="1.6.*" GeneratePathProperty="true" />
    <PackageReference Include="Lib.Harmony" Version="2.3.6" ExcludeAssets="runtime" />
  </ItemGroup>

  <ItemGroup>
    <Publicize Include="Assembly-CSharp:Verse.Pawn.Tick" />
  </ItemGroup>

</Project>




